version: "3.1"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mikudos_message_pusher
      MYSQL_USER: message_pusher
      MYSQL_PASSWORD: message_pusher
      MYSQL_ROOT_PASSWORD: MikudosMessagePusherServerPassword
    volumes:
      - "$PWD/data/mysql:/var/lib/mysql"
  adminer:
    image: adminer
    # restart: always
    ports:
      - 8080:8080
  redis:
    container_name: mikudos-redis
    image: redis
    ports:
      - "6379:6379"
