# Copyright (c) All contributors. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
# message pusher config file
# port is this grpc serivce listened
port: 50051
####################
# PUSH MODE
# support values are: "unify", "group", "every"
# At unify mode, message pusher will send one time randomly per message, this mode passt to the unify adapted mikudos gate
# At group mode, message pusher will use the groupId value keyed with group in META_DATA, which is send with from mikudos gate or other grpc message pusher client.
# At every mode, message pusher will send message to every mikudos gate, which is connected to the message pusher service.
# default value is "unify"
####################
mode: "group"
####################
# storageType set the storage engine for message.
# supported values are: "redis", "mysql"
# strong suggest to use redis as storage engine
####################
storageType: "redis"
####################
# redis storage node config
####################
redisSource:
  "node1:1": "tcp@localhost:6379"
####################
# mysql storage node config
####################
mySQLSource:
  "node1:1": "root:MikudosMessagePusherServerPassword@(127.0.0.1:3306)/mikudos_message_pusher?parseTime=true&loc=Local&charset=utf8"
